//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        public int RequestID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Reason { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> Emergent { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
